// Mock data for restaurants
export const mockRestaurants = [
  {
    id: 1,
    name: "Himalayan Kitchen",
    cloudinaryImageId:
      "https://images.unsplash.com/photo-1728910107534-e04e261768ae?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bmVwYWxpJTIwaW5kaWFuJTIwcmVzdGF1cmFudHxlbnwwfDJ8MHx8fDA%3D",
    description:
      "Authentic Nepali cuisine in a cozy atmosphere. Known for their momos and thalis.",
    avgRating: 4.7,
    cuisines: ["Nepali", "Indian", "Tibetan"],
    sla: {
      deliveryTime: 30,
      lastMileTravel: 2.5,
      serviceability: "SERVICEABLE",
      distance: "2.5 km",
      slaString: "25-30 mins",
    },
  },
  {
    id: 2,
    name: "Kathmandu Cafe",
    cloudinaryImageId:
      "https://images.unsplash.com/photo-1728910156510-77488f19b152?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8bmVwYWxpJTIwaW5kaWFuJTIwcmVzdGF1cmFudHxlbnwwfDJ8MHx8fDA%3D",
    description:
      "Modern take on traditional Nepali dishes. Great for lunch and dinner.",
    avgRating: 4.5,
    cuisines: ["Nepali", "Asian", "Fusion"],
    sla: {
      deliveryTime: 25,
      lastMileTravel: 1.8,
      serviceability: "SERVICEABLE",
      distance: "1.8 km",
      slaString: "20-25 mins",
    },
  },
  {
    id: 3,
    name: "Everest Dining",
    cloudinaryImageId:
      "https://images.unsplash.com/photo-1704642220407-392955316c7a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fG5lcGFsaSUyMGluZGlhbiUyMHJlc3RhdXJhbnR8ZW58MHwyfDB8fHww",
    description:
      "Family-owned restaurant serving home-style Nepali food with a view.",
    avgRating: 4.3,
    cuisines: ["Nepali", "Indian"],
    sla: {
      deliveryTime: 40,
      lastMileTravel: 3.5,
      serviceability: "SERVICEABLE",
      distance: "3.5 km",
      slaString: "35-40 mins",
    },
  },
  {
    id: 4,
    name: "Namaste Nepal",
    cloudinaryImageId:
      "https://images.unsplash.com/photo-1736680056361-6a2f6e35fa50?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fG5lcGFsaSUyMGluZGlhbiUyMHJlc3RhdXJhbnR8ZW58MHwyfDB8fHww",
    description:
      "Fusion of Nepali and Indian cuisine. Famous for their butter chicken and naan.",
    avgRating: 4.6,
    cuisines: ["Nepali", "Indian", "Fusion"],
    sla: {
      deliveryTime: 35,
      lastMileTravel: 4.2,
      lastMileTravelString: "4.2 km",
      serviceability: "SERVICEABLE",
      slaString: "30-35 mins",
    },
  },
];

// Mock data for recipes
export const mockRecipes = [
  {
    id: 1,
    title: "Authentic Chicken Momo",
    cloudinaryImageId: "/placeholder.svg?height=300&width=400",
    description:
      "Delicious Nepali dumplings filled with spiced chicken and served with tomato chutney.",
    avgRating: 4.8,
    category: "Appetizers",
    ingredients: [
      "2 cups all-purpose flour",
      "1 lb ground chicken",
      "1 onion, finely chopped",
      "2 cloves garlic, minced",
      "1 inch ginger, grated",
      "1/2 cup cilantro, chopped",
      "Salt and pepper to taste",
      "2 tbsp oil",
    ],
    instructions: [
      "Mix flour and water to make a smooth dough. Cover and let it rest for 30 minutes.",
      "In a bowl, combine ground chicken, onion, garlic, ginger, cilantro, salt, and pepper.",
      "Roll the dough into small circles and place a spoonful of filling in the center.",
      "Fold and pleat the edges to form dumplings.",
      "Steam for 15-20 minutes until cooked through.",
      "Serve hot with tomato chutney.",
    ],
  },
  {
    id: 2,
    title: "Dal Bhat",
    cloudinaryImageId: "/placeholder.svg?height=300&width=400",
    description:
      "The national dish of Nepal consisting of lentil soup, rice, and various side dishes.",
    avgRating: 4.6,
    category: "Main Course",
    ingredients: [
      "1 cup yellow lentils",
      "2 cups rice",
      "1 onion, chopped",
      "2 tomatoes, chopped",
      "2 cloves garlic, minced",
      "1 inch ginger, grated",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "Salt to taste",
      "2 tbsp ghee or oil",
    ],
    instructions: [
      "Rinse lentils and rice separately.",
      "Cook rice according to package instructions.",
      "In a pot, cook lentils with turmeric and salt until soft.",
      "In a separate pan, heat ghee and add cumin seeds.",
      "Add onion, garlic, and ginger. Sauté until golden brown.",
      "Add tomatoes and cook until soft.",
      "Add the tempering to the cooked lentils and simmer for 5 minutes.",
      "Serve hot with rice and your choice of side dishes.",
    ],
  },
  {
    id: 3,
    title: "Sel Roti",
    cloudinaryImageId: "/placeholder.svg?height=300&width=400",
    description:
      "Traditional Nepali sweet ring-shaped rice bread, typically served during festivals.",
    avgRating: 4.5,
    category: "Desserts",
    ingredients: [
      "2 cups rice flour",
      "1 cup sugar",
      "1/2 cup milk",
      "1/4 cup water",
      "1 tsp cardamom powder",
      "Oil for deep frying",
    ],
    instructions: [
      "Soak rice for 4-6 hours, then drain and grind to a paste.",
      "Mix rice paste with sugar, milk, water, and cardamom powder.",
      "Let the batter rest for 30 minutes.",
      "Heat oil in a deep pan.",
      "Pour the batter in a circular motion to form rings.",
      "Fry until golden brown on both sides.",
      "Drain on paper towels and serve warm.",
    ],
  },
  {
    id: 4,
    title: "Aloo Tama",
    cloudinaryImageId: "/placeholder.svg?height=300&width=400",
    description:
      "A tangy and spicy curry made with potatoes, bamboo shoots, and black-eyed peas.",
    avgRating: 4.4,
    category: "Main Course",
    ingredients: [
      "2 potatoes, cubed",
      "1 cup bamboo shoots",
      "1/2 cup black-eyed peas, soaked overnight",
      "1 onion, chopped",
      "2 tomatoes, chopped",
      "2 cloves garlic, minced",
      "1 inch ginger, grated",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "Salt to taste",
      "2 tbsp oil",
    ],
    instructions: [
      "Boil black-eyed peas until soft. Drain and set aside.",
      "Heat oil in a pan and add cumin seeds.",
      "Add onion, garlic, and ginger. Sauté until golden brown.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili powder, and salt.",
      "Add potatoes and cook for 5 minutes.",
      "Add bamboo shoots and black-eyed peas.",
      "Add water and simmer until potatoes are cooked.",
      "Serve hot with rice or roti.",
    ],
  },
  {
    id: 5,
    title: "Gundruk Soup",
    cloudinaryImageId: "/placeholder.svg?height=300&width=400",
    description:
      "A traditional fermented leafy green soup that is tangy and full of probiotics.",
    avgRating: 4.2,
    category: "Soups",
    ingredients: [
      "1 cup gundruk (fermented leafy greens)",
      "1 onion, chopped",
      "2 tomatoes, chopped",
      "2 cloves garlic, minced",
      "1 inch ginger, grated",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "Salt to taste",
      "2 tbsp oil",
    ],
    instructions: [
      "Soak gundruk in water for 10 minutes, then drain.",
      "Heat oil in a pan and add cumin seeds.",
      "Add onion, garlic, and ginger. Sauté until golden brown.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili powder, and salt.",
      "Add gundruk and 4 cups of water.",
      "Simmer for 15-20 minutes.",
      "Serve hot with rice or bread.",
    ],
  },
  {
    id: 6,
    title: "Yomari",
    cloudinaryImageId: "/placeholder.svg?height=300&width=400",
    description:
      "A sweet dumpling made from rice flour and filled with molasses and sesame seeds.",
    avgRating: 4.7,
    category: "Desserts",
    ingredients: [
      "2 cups rice flour",
      "1 cup water",
      "1 cup molasses or jaggery",
      "1/2 cup sesame seeds",
      "1/4 cup coconut, grated",
      "1 tsp cardamom powder",
    ],
    instructions: [
      "Mix rice flour with hot water to make a smooth dough.",
      "In a separate pan, heat molasses until it melts.",
      "Add sesame seeds, coconut, and cardamom powder. Mix well.",
      "Take a small portion of dough and flatten it.",
      "Place a spoonful of filling in the center.",
      "Fold and shape into a cone or fish shape.",
      "Steam for 15-20 minutes until cooked.",
      "Serve warm as a dessert or snack.",
    ],
  },
  {
    id: 7,
    title: "Thukpa",
    cloudinaryImageId: "/placeholder.svg?height=300&width=400",
    description:
      "A hearty noodle soup with vegetables and meat, popular in the Himalayan regions.",
    avgRating: 4.5,
    category: "Soups",
    ingredients: [
      "200g noodles",
      "1 cup chicken or vegetables, chopped",
      "1 onion, sliced",
      "2 carrots, julienned",
      "1 bell pepper, sliced",
      "2 cloves garlic, minced",
      "1 inch ginger, grated",
      "4 cups chicken or vegetable broth",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "Salt and pepper to taste",
      "2 tbsp oil",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "Heat oil in a pot and add garlic and ginger.",
      "Add onions and sauté until translucent.",
      "Add chicken or vegetables and cook for 5 minutes.",
      "Add turmeric, red chili powder, salt, and pepper.",
      "Pour in the broth and bring to a boil.",
      "Add noodles and cook until tender.",
      "Garnish with fresh cilantro and serve hot.",
    ],
  },
  {
    id: 8,
    title: "Chatamari",
    cloudinaryImageId: "/placeholder.svg?height=300&width=400",
    description:
      "A Newari rice flour crepe topped with various savory ingredients.",
    avgRating: 4.6,
    category: "Appetizers",
    ingredients: [
      "2 cups rice flour",
      "1 cup water",
      "1/2 cup minced meat or vegetables",
      "1 onion, finely chopped",
      "2 cloves garlic, minced",
      "1 inch ginger, grated",
      "1 egg (optional)",
      "Salt and pepper to taste",
      "2 tbsp oil",
    ],
    instructions: [
      "Mix rice flour with water to make a thin batter.",
      "Heat a non-stick pan and pour a ladleful of batter.",
      "Spread it thin like a crepe and cook on low heat.",
      "In a separate pan, sauté meat or vegetables with onion, garlic, and ginger.",
      "Spread the mixture over the half-cooked crepe.",
      "If using egg, crack it on top and spread it around.",
      "Cover and cook until the toppings are cooked.",
      "Fold or roll and serve hot.",
    ],
  },
  {
    id: 9,
    title: "Dhido",
    cloudinaryImageId: "/placeholder.svg?height=300&width=400",
    description:
      "A traditional Nepali dish made from buckwheat or millet flour, similar to polenta.",
    avgRating: 4.3,
    category: "Main Course",
    ingredients: [
      "2 cups buckwheat or millet flour",
      "4 cups water",
      "Salt to taste",
      "Ghee for serving",
    ],
    instructions: [
      "Bring water to a boil in a pot.",
      "Add salt and slowly add flour while stirring continuously.",
      "Keep stirring until the mixture thickens and pulls away from the sides of the pot.",
      "Continue cooking for 10-15 minutes, stirring occasionally.",
      "Serve hot with ghee and your choice of curry or pickle.",
    ],
  },
];
